### ISSUE TITLE
Spotify user vs Spotify current user

### ISSUE THREAD

**Issue by Travis-Preston** [WSU-4110/Spicify#28]
When I run workoutplaylist.py or GeneralDrivingPlaylist.py or StudyPlaylist.py it creates a playlist on Gianna's Spotify account even though I am logged into mine.

**Comment by gia-marchetti** [comment]
This bug was solved by deleting the cache and then re-running the project on each of our own machines and going through the authentication process. This bug was due to to spotipy having a complex authentication process and each of us testing on our own systems
